import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },

        /* Morphic palette */
        'absolute-zero': 'var(--color-absolute-zero)',
        'morphic-teal': 'var(--color-morphic-teal)',
        'morphic-teal-hover': 'var(--color-morphic-teal-hover)',
        'morphic-aqua': 'var(--color-morphic-aqua)',
        'morphic-aqua-hover': 'var(--color-morphic-aqua-hover)',
        'morphic-blue': 'var(--color-morphic-blue)',
        'morphic-blue-hover': 'var(--color-morphic-blue-hover)',
        'morphic-green': 'var(--color-morphic-green)',
        'morphic-green-hover': 'var(--color-morphic-green-hover)',
        'ebony-canvas': 'var(--color-ebony-canvas)',
        'nightfall-gray': 'var(--color-nightfall-gray)',
        'charcoal-surface': 'var(--color-charcoal-surface)',
        'deep-graphite': 'var(--color-deep-graphite)',
        'cloud-white': 'var(--color-cloud-white)',
        'light-mist': 'var(--color-light-mist)',
        'outline-haze': 'var(--color-outline-haze)',
        'muted-silver': 'var(--color-muted-silver)',
        'subtle-gray': 'var(--color-subtle-gray)',
        'anchor-graphite': 'var(--color-anchor-graphite)',
        'dim-gray': 'var(--color-dim-gray)',

        /* Legacy aliases (kept so existing code keeps working) */
        'midnight-oil': 'var(--color-ebony-canvas)',
        'ghost-white': 'var(--color-cloud-white)',
        'steel-gray': 'var(--color-nightfall-gray)',
        'muted-ash': 'var(--color-charcoal-surface)',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'var(--font-geist)', 'Inter', 'Geist', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        geist: ['var(--font-geist)', 'Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        inter: ['var(--font-inter)', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'soehne-mono': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      fontSize: {
        'caption': ['10px', { lineHeight: '1.5', letterSpacing: '-0.1px' }],
        'body': ['14px', { lineHeight: '1.33', letterSpacing: '-0.22px' }],
        'body-lg': ['16px', { lineHeight: '1.29', letterSpacing: '-0.256px' }],
        'subheading': ['18px', { lineHeight: '1.2', letterSpacing: '-0.27px' }],
        'heading': ['20px', { lineHeight: '1.15', letterSpacing: '-0.28px' }],
        'heading-lg': ['40px', { lineHeight: '1.17', letterSpacing: '-0.96px' }],
        'display': ['52px', { lineHeight: '1', letterSpacing: '-1.352px' }],
      },
      spacing: {
        '5-px': '5px',
        '6-px': '6px',
        '8-px': '8px',
        '12-px': '12px',
        '16-px': '16px',
        '19': '19px',
        '20-px': '20px',
        '24-px': '24px',
        '26': '26px',
        '27': '27px',
        '28-px': '28px',
        '32-px': '32px',
        '40-px': '40px',
        '60-px': '60px',
        '72-px': '72px',
        '80-px': '80px',
        '96-px': '96px',
        '100-px': '100px',
        '140-px': '140px',
        '180-px': '180px',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        lg: 'var(--radius)',
        'cards': '10px',
        'inputs': '10px',
        'buttons': '7px',
        'large': '16px',
        'super-large': '24px',
        'hero': '32px',
        'pill': '100px',
        'lg-099': 'var(--radius-lg)',
      },
      boxShadow: {
        'xl-morphic': 'rgba(0, 0, 0, 0.1) 0px 20px 25px -5px, rgba(0, 0, 0, 0.1) 0px 8px 10px -6px',
      },
    },
  },
  plugins: [],
};
export default config;
